### ISSUE TITLE
What do you do?

### ISSUE THREAD

**Issue by russiaparadise** [Enum0x539/Qvoid-Token-Grabber#11]
Hey, I'm pretty new to these type of things and I was wondering on how to first start? Maybe a set of instructions? Thanks.

**Comment by Enum0x539** [comment]
"This project was started because I wanted to learn about Discord's infrastructure and possible exploits, mean-while I made the base of this token-grabber (like a year ago) but, not long ago I continued this project and this is the final result."
I wrote it in the main page.

Anyway I keep learning about Discord, so I implementing the stuff I learned into the project; I don't know if I will upload the new version because it will be too powerful for free...
