### ISSUE TITLE
Nothing working 

### ISSUE THREAD

**Issue by Therealloli101** [Enum0x539/Qvoid-Token-Grabber#21]
Well, i tested it in a vm and it worked perfectly fine but today i was trying to logg someone and nothing happened, i tried 6 times (every time new built) and nothing happened, and in the vm it also didn't work

**Comment by Enum0x539** [comment]
It didn't worked on the VM in the second time because there is filter system, for the rest I have nothing to do because for me it's working perfectly and I need someone with the problem to debug it...

Anyway answer my questions if you can (or ask the one who it didn't worked for him):
1) What browsers you have installed?
2) What distribute of Windows you using?
3) What build of Discord you using (if you have couple so all of them)?
4) You have betterdiscord installed?
5) Is your anti-virus disabled?

**Comment by Enum0x539** [comment]
Fixed.
